version: '3'
services:
  go-server:
    image: gocd/gocd-server:v19.2.0
    ports:
      - "8153:8153"
      - "8154:8154"
    # volumes:
    #   - ./godata/config/cruise-config.xml:/godata/config/cruise-config.xml
    logging:
      driver: awslogs
      options: 
        awslogs-group: tutorial
        awslogs-region: us-west-1
        awslogs-stream-prefix: gocd-chris