version: '2'
services:
  go-server:
    image: gocd/gocd-server:v19.1.0
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - ./godata/config/cruise-config.xml:/godata/config/cruise-config.xml
  go-agent1:
    image: gocd/gocd-agent-alpine-3.8:v19.1.0
    links:
      - "go-server"
    depends_on:
      - "go-server"
    environment:
      AGENT_AUTO_REGISTER_KEY: 'defaultAutoAgentRegisterKeyChangeMe'
      GO_SERVER_URL: https://go-server:8154/go
  # go-agent2:
  #   image: gocd/gocd-agent-alpine-3.8:v19.1.0
  #   links:
  #     - "go-server"
  #   depends_on:
  #     - "go-server"
  #   environment:
  #     AGENT_AUTO_REGISTER_KEY: 'defaultAutoAgentRegisterKeyChangeMe'
  #     GO_SERVER_URL: https://go-server:8154/go